### ISSUE TITLE
Corrections Vectors.rst

### ISSUE THREAD

**Issue by jtheinen** [moorepants/learn-multibody-dynamics#14]
## What is a vector?
- Line 50: scalar multiplicative & common orientation actually say the same thing

## Vector functions
- Line 78-80: What do you mean by: 𝑣¯  is a vector function of scalar variable 𝑞 in reference frame 𝐴 if 𝑣¯ changes when viewed in 𝐴 when 𝑞 changes.
- Line 84: Staring -> Starting
- It seems a bit complex, maybe show a drawing that 𝑣¯ can be projected to a certain frame i.e. express 𝑣¯ in A

## Addition
- Line 163: measure numbers = scalars

## Dot product
- Line 310: Maybe add (i.e. w^) after w¯

## Cross product
- line 382-384: in v¯ x w¯ , put brackets between answer and unit vector
- line 395: crossing vector with itself: change to a¯ x a¯  = 0¯ 

## Vectors Expressed in Multiple Reference Frames
- line 489: delete 'But'

## Relative Position Among Points
- Exercise does not have 'Solution     Click to show'
- line 568: change 'write position vectors relating pairs of points...' to ' write position vectors between pairs of points...'

**Comment by moorepants** [comment]
>  Line 50: scalar multiplicative & common orientation actually say the same thing

combined

> Line 78-80: What do you mean by: 𝑣¯ is a vector function of scalar variable 𝑞 in reference frame 𝐴 if 𝑣¯ changes when viewed in 𝐴 when 𝑞 changes.

I reworded this to make it less like Kane's statement.

> It seems a bit complex, maybe show a drawing that 𝑣¯ can be projected to a certain frame i.e. express 𝑣¯ in A

Yeh, this is Kane speak, which is often too complex. I tried to simplify it a bit and added some language about expressing and projections.

>  Line 163: measure numbers = scalars

I'm going to stick with measure numbers since I defined it before. measure number means more than just scalar as defined

>  Line 310: Maybe add (i.e. w^) after w¯

Done.

> line 382-384: in v¯ x w¯ , put brackets between answer and unit vector
like this:
![image](https://user-images.githubusercontent.com/276007/154559143-11fe4114-295f-4623-bac2-c93878a934bf.png)

> line 395: crossing vector with itself: change to a¯ x a¯ = 0¯

Fixed.

> Exercise does not have 'Solution Click to show'

I show how to find this with sympy below, so they can do this, but I added a todo, I may add a solution later.

> line 568: change 'write position vectors relating pairs of points...' to ' write position vectors between pairs of points...'

Done.

**Comment by moorepants** [comment]
I have a todo for the solution, so closing. Thanks!
